"""
Django settings for drfDemo project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import rest_framework
import django_filters
import drf_yasg
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3n%#=o)uj==7a6ywl(t=+c8yd^3)6fjzq-o!$vl8(%g!bcuffx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'drf_yasg',
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'students',  # 原生接口
    'stuapi',  # 调用 api
    'sers',  # models serializers模型
    'req',  # rest 里面的请求类
    'demo',  # 视图
    'school',  # 序列化嵌套
    'opt',  # 序列化嵌套
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drfDemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drfDemo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'drf',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': 'admin*123'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# drf 配置

REST_FRAMEWORK = {
    # # 认证
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     # 基础认证
    #     'rest_framework.authentication.BasicAuthentication',
    #     # session认证
    #     'rest_framework.authentication.SessionAuthentication',
    #     # # token认证
    #     # 'rest_framework.authentication.TokenAuthentication',
    #     # 自定义验证
    #     'drfDemo.authentication.CustomAuthentication'
    # ),
    #
    # # 权限
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     # 但是会有个小问题 就是你在登陆页面 会让你去登陆 可以使用在登陆的视图类中设置 permission_classes=[]
    #     'rest_framework.permissions.IsAuthenticated',  # 大部分公司企业的内部站点都是使用这个 不允许其他人访问 都会默认全局设置
    #     # 'drfDemo.permission.IsXiaoMingPermission',
    # ),

    # # 限流
    'DEFAULT_THROTTLE_CLASSES': (
        # 'rest_framework.throttling.AnonRateThrottle', # 未登录用户
        # 'rest_framework.throttling.UserRateThrottle',    #登录用户
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '2/day',  # 未登录用户 每天100次
        'user': '4/day',  # 登录用户每天1000次
        'member': "3/day",
        'vip': "3/hour",
        'vvip': "3/minute",
    },
    # # 过滤器默认后端
    # 'DEFAULT_FILTER_BACKENDS': (
    #     # 'django_filters.rest_framework.DjangoFilterBackend', # 过滤
    #     'rest_framework.filters.OrderingFilter',
    # ),


    # 分页全局配置 基本不用
    # # 偏移量分页器
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # # 页码分页器
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5, # 每一页多少条数据 如果不进行设置 则不分配,

    'EXCEPTION_HANDLER': 'drfDemo.exceptions.exceptions_custom',
'DEFAULT_SCHEMA_CLASS':'rest_framework.schemas.coreapi.AutoSchema'

}
