# Generated by Django 3.2.12 on 2022-02-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=255, verbose_name='姓名')),
                ('gender', models.BooleanField(default=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('classNum', models.CharField(max_length=10, verbose_name='班级')),
                ('description', models.CharField(max_length=32, verbose_name='个性签名')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
                'db_table': 'tb_student',
            },
        ),
    ]
